### ISSUE TITLE
Database connection path not found

### ISSUE THREAD

**Issue by Westdespair** [Westdespair/bike_rental_service#11]
The database and backend are currently not connected, and gets error messages on query attempts. Fix path so that the database and backend can connect properly, or create a proper reference to the path. 

**Stacktrace on query attempt:** 
Connection success!
Connection success!
Exception in thread "main" org.sqlite.SQLiteException: [SQLITE_ERROR] SQL error or missing database (no such table: Bikes)
	at org.sqlite.core.DB.newSQLException(DB.java:1030)
	at org.sqlite.core.DB.newSQLException(DB.java:1042)
	at org.sqlite.core.DB.throwex(DB.java:1007)
	at org.sqlite.core.NativeDB.prepare_utf8(Native Method)
	at org.sqlite.core.NativeDB.prepare(NativeDB.java:137)
	at org.sqlite.core.DB.prepare(DB.java:257)
	at org.sqlite.jdbc3.JDBC3Statement.executeQuery(JDBC3Statement.java:66)
	at no.ntnu.bikerental.DatabaseQueries.getAnyAvailableBike(DatabaseQueries.java:52)
	at no.ntnu.bikerental.DBTestApp.main(DBTestApp.java:14)

Process finished with exit code 1

**Comment by Westdespair** [comment]
This issue was fixed in commit 16f79d1d396c2ede5c02533122385528571cbf87
